# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import communication_pb2 as communication__pb2

GRPC_GENERATED_VERSION = "1.75.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in communication_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class CommunicationServiceStub(object):
    """Service definition for agent communication"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
            "/communication.grpc.CommunicationService/SendMessage",
            request_serializer=communication__pb2.SendMessageRequest.SerializeToString,
            response_deserializer=communication__pb2.SendMessageResponse.FromString,
            _registered_method=True,
        )
        self.BroadcastMessage = channel.unary_unary(
            "/communication.grpc.CommunicationService/BroadcastMessage",
            request_serializer=communication__pb2.BroadcastMessageRequest.SerializeToString,
            response_deserializer=communication__pb2.BroadcastMessageResponse.FromString,
            _registered_method=True,
        )
        self.GetMessages = channel.unary_unary(
            "/communication.grpc.CommunicationService/GetMessages",
            request_serializer=communication__pb2.GetMessagesRequest.SerializeToString,
            response_deserializer=communication__pb2.GetMessagesResponse.FromString,
            _registered_method=True,
        )
        self.RegisterAgent = channel.unary_unary(
            "/communication.grpc.CommunicationService/RegisterAgent",
            request_serializer=communication__pb2.RegisterAgentRequest.SerializeToString,
            response_deserializer=communication__pb2.RegisterAgentResponse.FromString,
            _registered_method=True,
        )
        self.AddCommunicationLink = channel.unary_unary(
            "/communication.grpc.CommunicationService/AddCommunicationLink",
            request_serializer=communication__pb2.AddLinkRequest.SerializeToString,
            response_deserializer=communication__pb2.AddLinkResponse.FromString,
            _registered_method=True,
        )
        self.GetStatistics = channel.unary_unary(
            "/communication.grpc.CommunicationService/GetStatistics",
            request_serializer=communication__pb2.StatisticsRequest.SerializeToString,
            response_deserializer=communication__pb2.StatisticsResponse.FromString,
            _registered_method=True,
        )
        self.GetTopology = channel.unary_unary(
            "/communication.grpc.CommunicationService/GetTopology",
            request_serializer=communication__pb2.TopologyRequest.SerializeToString,
            response_deserializer=communication__pb2.TopologyResponse.FromString,
            _registered_method=True,
        )
        self.StreamMessages = channel.stream_unary(
            "/communication.grpc.CommunicationService/StreamMessages",
            request_serializer=communication__pb2.SendMessageRequest.SerializeToString,
            response_deserializer=communication__pb2.StreamSummaryResponse.FromString,
            _registered_method=True,
        )


class CommunicationServiceServicer(object):
    """Service definition for agent communication"""

    def SendMessage(self, request, context):
        """Send a message from one agent to another"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BroadcastMessage(self, request, context):
        """Broadcast a message to all reachable agents"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetMessages(self, request, context):
        """Get messages from an agent's mailbox"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RegisterAgent(self, request, context):
        """Register an agent with the communication service"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AddCommunicationLink(self, request, context):
        """Add a communication link between two agents"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetStatistics(self, request, context):
        """Get communication statistics"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTopology(self, request, context):
        """Get topology information"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamMessages(self, request_iterator, context):
        """Client-streaming variant for high-throughput message sending"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CommunicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SendMessage": grpc.unary_unary_rpc_method_handler(
            servicer.SendMessage,
            request_deserializer=communication__pb2.SendMessageRequest.FromString,
            response_serializer=communication__pb2.SendMessageResponse.SerializeToString,
        ),
        "BroadcastMessage": grpc.unary_unary_rpc_method_handler(
            servicer.BroadcastMessage,
            request_deserializer=communication__pb2.BroadcastMessageRequest.FromString,
            response_serializer=communication__pb2.BroadcastMessageResponse.SerializeToString,
        ),
        "GetMessages": grpc.unary_unary_rpc_method_handler(
            servicer.GetMessages,
            request_deserializer=communication__pb2.GetMessagesRequest.FromString,
            response_serializer=communication__pb2.GetMessagesResponse.SerializeToString,
        ),
        "RegisterAgent": grpc.unary_unary_rpc_method_handler(
            servicer.RegisterAgent,
            request_deserializer=communication__pb2.RegisterAgentRequest.FromString,
            response_serializer=communication__pb2.RegisterAgentResponse.SerializeToString,
        ),
        "AddCommunicationLink": grpc.unary_unary_rpc_method_handler(
            servicer.AddCommunicationLink,
            request_deserializer=communication__pb2.AddLinkRequest.FromString,
            response_serializer=communication__pb2.AddLinkResponse.SerializeToString,
        ),
        "GetStatistics": grpc.unary_unary_rpc_method_handler(
            servicer.GetStatistics,
            request_deserializer=communication__pb2.StatisticsRequest.FromString,
            response_serializer=communication__pb2.StatisticsResponse.SerializeToString,
        ),
        "GetTopology": grpc.unary_unary_rpc_method_handler(
            servicer.GetTopology,
            request_deserializer=communication__pb2.TopologyRequest.FromString,
            response_serializer=communication__pb2.TopologyResponse.SerializeToString,
        ),
        "StreamMessages": grpc.stream_unary_rpc_method_handler(
            servicer.StreamMessages,
            request_deserializer=communication__pb2.SendMessageRequest.FromString,
            response_serializer=communication__pb2.StreamSummaryResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "communication.grpc.CommunicationService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "communication.grpc.CommunicationService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class CommunicationService(object):
    """Service definition for agent communication"""

    @staticmethod
    def SendMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/communication.grpc.CommunicationService/SendMessage",
            communication__pb2.SendMessageRequest.SerializeToString,
            communication__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def BroadcastMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/communication.grpc.CommunicationService/BroadcastMessage",
            communication__pb2.BroadcastMessageRequest.SerializeToString,
            communication__pb2.BroadcastMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetMessages(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/communication.grpc.CommunicationService/GetMessages",
            communication__pb2.GetMessagesRequest.SerializeToString,
            communication__pb2.GetMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RegisterAgent(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/communication.grpc.CommunicationService/RegisterAgent",
            communication__pb2.RegisterAgentRequest.SerializeToString,
            communication__pb2.RegisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AddCommunicationLink(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/communication.grpc.CommunicationService/AddCommunicationLink",
            communication__pb2.AddLinkRequest.SerializeToString,
            communication__pb2.AddLinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetStatistics(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/communication.grpc.CommunicationService/GetStatistics",
            communication__pb2.StatisticsRequest.SerializeToString,
            communication__pb2.StatisticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTopology(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/communication.grpc.CommunicationService/GetTopology",
            communication__pb2.TopologyRequest.SerializeToString,
            communication__pb2.TopologyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamMessages(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            "/communication.grpc.CommunicationService/StreamMessages",
            communication__pb2.SendMessageRequest.SerializeToString,
            communication__pb2.StreamSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
