"""
Battery Health Monitor Agent (BDI Architecture)

This module implements a BDI agent for battery health monitoring and assessment.
The agent tracks degradation trends, estimates remaining useful life (RUL),
and generates alerts for abnormal battery behavior.

Architecture:
- Beliefs: Health status, degradation rates, risk levels
- Desires: Maintain health, prevent failure, optimize lifetime
- Intentions: Monitoring schedule, alert plan

Author: Battery Twin Development Team
Date: 2025-03-01
"""

import json
import logging
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional, Tuple

import numpy as np
from pydantic import BaseModel, Field

from src.abstract_agent import AgentId, GoalType, Goal
from src.battery_twin.agents.battery_agent_types import BatteryBDIAgent
from src.battery_twin.communication.mqtt_bridge import MqttBridge
from src.battery_twin.storage.battery_storage_manager import BatteryStorageManager


# ============================================================================
# Health Status Enumerations
# ============================================================================

class HealthStatus(str, Enum):
    """Overall battery health status."""
    EXCELLENT = "EXCELLENT"  # >95% SoH, low degradation
    GOOD = "GOOD"            # 85-95% SoH, normal degradation
    FAIR = "FAIR"            # 70-85% SoH, elevated degradation
    POOR = "POOR"            # 50-70% SoH, high degradation
    CRITICAL = "CRITICAL"    # <50% SoH, imminent failure


class RiskLevel(str, Enum):
    """Risk level for battery failure or performance degradation."""
    LOW = "LOW"              # Nominal operation
    MEDIUM = "MEDIUM"        # Some degradation observed
    HIGH = "HIGH"            # Significant degradation
    CRITICAL = "CRITICAL"    # Failure imminent


class AlertType(str, Enum):
    """Types of health alerts."""
    CAPACITY_FADE = "CAPACITY_FADE"
    RESISTANCE_INCREASE = "RESISTANCE_INCREASE"
    LOW_RUL = "LOW_RUL"
    RAPID_DEGRADATION = "RAPID_DEGRADATION"
    TEMPERATURE_STRESS = "TEMPERATURE_STRESS"
    HEALTH_STATUS_CHANGE = "HEALTH_STATUS_CHANGE"


# ============================================================================
# Health Metrics Data Classes
# ============================================================================

@dataclass
class CapacityFadeMetrics:
    """Metrics for capacity fade analysis."""
    initial_soh: float
    current_soh: float
    fade_percent: float  # Total fade from initial
    fade_rate: float     # Percent per cycle
    cycles_observed: int
    timestamp: datetime


@dataclass
class ResistanceMetrics:
    """Metrics for resistance increase analysis."""
    initial_r0: float
    current_r0: float
    increase_percent: float
    increase_rate: float  # Ohms per cycle
    cycles_observed: int
    timestamp: datetime


@dataclass
class RULEstimate:
    """Remaining Useful Life estimate."""
    rul_cycles: float          # Expected remaining cycles
    rul_days: Optional[float]  # Expected remaining days (if usage known)
    confidence: float          # 0-1 confidence in estimate
    eol_threshold: float       # End-of-life SoH threshold (e.g., 0.8)
    timestamp: datetime


@dataclass
class HealthAlert:
    """Health alert generated by the agent."""
    alert_type: AlertType
    severity: RiskLevel
    message: str
    timestamp: datetime
    metrics: Dict  # Supporting metrics
    recommended_action: Optional[str] = None


# ============================================================================
# Pydantic Message Schemas
# ============================================================================

class StateEstimateMessage(BaseModel):
    """Message from StateEstimatorAgent with EKF estimates."""
    battery_id: str
    cycle: int
    timestamp: float
    soc: float
    soh: float
    r0: float
    r1: float
    c1: float
    v1: float
    soc_uncertainty: float
    soh_uncertainty: float
    confidence_level: str
    filter_health: str


class HealthReportMessage(BaseModel):
    """Health report published by HealthMonitorAgent."""
    battery_id: str
    timestamp: float
    health_status: str
    risk_level: str
    soh: float
    capacity_fade_percent: float
    capacity_fade_rate: float
    resistance_increase_percent: float
    rul_cycles: float
    rul_confidence: float
    alerts: List[Dict] = Field(default_factory=list)
    recommendations: List[str] = Field(default_factory=list)


# ============================================================================
# HealthMonitorAgent (BDI)
# ============================================================================

class HealthMonitorAgent(BatteryBDIAgent):
    """
    BDI agent for battery health monitoring and assessment.

    Beliefs:
        - health_status: Current overall health (EXCELLENT to CRITICAL)
        - degradation_rate: Rate of capacity fade and resistance increase
        - risk_level: Current risk level (LOW to CRITICAL)
        - current_soh: Latest State of Health from estimates
        - current_resistance: Latest R0 from estimates
        - rul_estimate: Remaining Useful Life estimate
        - alert_history: Recent alerts generated

    Goals:
        - maintain_health: Keep battery in good health status
        - prevent_failure: Avoid critical states
        - optimize_lifetime: Maximize remaining useful life

    Intentions:
        - monitoring_schedule: Regular health assessment
        - alert_plan: Generate timely alerts
    """

    def __init__(
        self,
        agent_id: AgentId,
        battery_id: str,
        initial_soh: float = 1.0,
        initial_r0: float = 0.01,
        eol_threshold: float = 0.8,
        mqtt_bridge: Optional[MqttBridge] = None,
        storage_manager: Optional[BatteryStorageManager] = None,
        observable_properties: Optional[set] = None
    ):
        """
        Initialize HealthMonitorAgent.

        Args:
            agent_id: Unique agent identifier
            battery_id: Battery being monitored
            initial_soh: Initial State of Health (typically 1.0)
            initial_r0: Initial internal resistance (Ohms)
            eol_threshold: End-of-life SoH threshold (default 0.8 = 80%)
            mqtt_bridge: MQTT communication bridge
            storage_manager: Optional storage manager
            observable_properties: Properties to track
        """
        # Store battery_id before super init
        self.battery_id = battery_id

        super().__init__(
            agent_id=agent_id,
            observable_properties=observable_properties or {
                "health_status", "risk_level", "rul_estimate"
            },
            mqtt_bridge=mqtt_bridge,
            storage_manager=storage_manager
        )

        self.logger = logging.getLogger(f"HealthMonitor.{battery_id}")

        # Health monitoring parameters
        self.initial_soh = initial_soh
        self.initial_r0 = initial_r0
        self.eol_threshold = eol_threshold

        # Thresholds for alerts
        self.capacity_fade_alert_threshold = 0.05  # 5% fade triggers alert
        self.resistance_increase_alert_threshold = 0.20  # 20% increase triggers alert
        self.rapid_degradation_threshold = 0.001  # 0.1% fade per cycle
        self.low_rul_threshold = 100  # Alert when RUL < 100 cycles

        # Historical data for trend analysis
        self.soh_history: List[Tuple[int, float, datetime]] = []  # (cycle, soh, time)
        self.r0_history: List[Tuple[int, float, datetime]] = []   # (cycle, r0, time)
        self.alert_history: List[HealthAlert] = []

        # Current metrics
        self.current_cycle = 0
        self.latest_capacity_fade: Optional[CapacityFadeMetrics] = None
        self.latest_resistance: Optional[ResistanceMetrics] = None
        self.latest_rul: Optional[RULEstimate] = None

        # Statistics
        self.total_alerts_generated = 0
        self.total_assessments = 0

        # Initialize BDI components
        self._initialize_beliefs()
        self._initialize_goals()
        self._initialize_intentions()

        # MQTT subscriptions (if mqtt_bridge is available)
        if mqtt_bridge:
            self._setup_subscriptions()

        self.logger.info(
            f"HealthMonitorAgent initialized for {battery_id}, "
            f"initial_soh={initial_soh:.3f}, eol_threshold={eol_threshold:.2f}"
        )

    # ========================================================================
    # BDI Initialization
    # ========================================================================

    def _initialize_beliefs(self):
        """Initialize beliefs about battery health."""
        self.state.update_belief(
            key='health_status',
            proposition=f"status_{HealthStatus.EXCELLENT.value}",
            confidence=1.0,
            is_internal=True
        )
        self.state.update_belief(
            key='risk_level',
            proposition=f"risk_{RiskLevel.LOW.value}",
            confidence=1.0,
            is_internal=True
        )
        self.state.update_belief(
            key='current_soh',
            proposition=f"soh_{self.initial_soh:.4f}",
            confidence=1.0,
            is_internal=True
        )
        self.state.update_belief(
            key='current_r0',
            proposition=f"r0_{self.initial_r0:.6f}",
            confidence=1.0,
            is_internal=True
        )
        self.state.update_belief(
            key='capacity_fade_rate',
            proposition=f"fade_rate_0.0000",
            confidence=0.5,  # Low confidence initially
            is_internal=True
        )
        self.state.update_belief(
            key='resistance_increase_rate',
            proposition=f"resistance_rate_0.0000",
            confidence=0.5,
            is_internal=True
        )
        self.state.update_belief(
            key='rul_cycles',
            proposition=f"rul_infinite",
            confidence=0.0,  # Unknown initially
            is_internal=True
        )
        self.state.update_belief(
            key='alert_count',
            proposition=f"alerts_0",
            confidence=1.0,
            is_internal=True
        )

        self.logger.debug("Health beliefs initialized")

    def _initialize_goals(self):
        """Initialize goals for health monitoring."""
        # Goal 1: Maintain good health status
        self.add_goal(Goal(
            condition="maintain_health",
            goal_type=GoalType.PERFORMANCE,
            priority=0.9
        ))

        # Goal 2: Prevent failure (critical states)
        self.add_goal(Goal(
            condition="prevent_failure",
            goal_type=GoalType.PERFORMANCE,
            priority=1.0  # Highest priority
        ))

        # Goal 3: Optimize lifetime (maximize RUL)
        self.add_goal(Goal(
            condition="optimize_lifetime",
            goal_type=GoalType.PERFORMANCE,
            priority=0.7
        ))

        self.logger.debug(f"Initialized {len(self.goals)} health goals")

    def _initialize_intentions(self):
        """Initialize intentions for health monitoring."""
        # Intention 1: Regular monitoring schedule
        self.intentions.append({
            'name': 'monitoring_schedule',
            'description': 'Assess health on every state estimate',
            'active': True,
            'priority': 0.9
        })

        # Intention 2: Alert plan
        self.intentions.append({
            'name': 'alert_plan',
            'description': 'Generate timely alerts for degradation',
            'active': True,
            'priority': 1.0
        })

        self.logger.debug(f"Initialized {len(self.intentions)} intentions")

    # ========================================================================
    # MQTT Subscription Setup
    # ========================================================================

    def _setup_subscriptions(self):
        """Subscribe to relevant MQTT topics."""
        # Subscribe to state estimates from StateEstimatorAgent
        state_topic = f"battery/{self.battery_id}/state/estimate"
        self.mqtt_bridge.subscribe(state_topic, self._handle_state_estimate)

        # Could also subscribe to physics/hybrid predictions if needed
        # prediction_topic = f"battery/{self.battery_id}/prediction/hybrid"
        # self.mqtt_bridge.subscribe(prediction_topic, self._handle_prediction)

        self.logger.info(f"Subscribed to {state_topic}")

    # ========================================================================
    # Message Handlers
    # ========================================================================

    def _handle_state_estimate(self, topic: str, payload: str):
        """
        Handle incoming state estimate from StateEstimatorAgent.

        Args:
            topic: MQTT topic
            payload: JSON message payload
        """
        try:
            msg = StateEstimateMessage.model_validate_json(payload)

            self.logger.debug(
                f"Received state estimate: cycle={msg.cycle}, "
                f"soh={msg.soh:.4f}, r0={msg.r0:.6f}"
            )

            # Update current cycle
            self.current_cycle = msg.cycle

            # Update beliefs with latest estimates
            self.state.update_belief(
                key='current_soh',
                proposition=f"soh_{msg.soh:.4f}",
                confidence=0.95,
                is_internal=True
            )
            self.state.update_belief(
                key='current_r0',
                proposition=f"r0_{msg.r0:.6f}",
                confidence=0.95,
                is_internal=True
            )

            # Add to history
            timestamp = datetime.fromtimestamp(msg.timestamp)
            self.soh_history.append((msg.cycle, msg.soh, timestamp))
            self.r0_history.append((msg.cycle, msg.r0, timestamp))

            # Perform health assessment
            self._assess_health(msg)

            # Deliberate on alerts
            self._deliberate_on_alerts()

            # Publish health report
            self._publish_health_report(msg.timestamp)

            self.total_assessments += 1

        except Exception as e:
            self.logger.error(f"Error handling state estimate: {e}", exc_info=True)

    # ========================================================================
    # Health Assessment
    # ========================================================================

    def _assess_health(self, state_msg: StateEstimateMessage):
        """
        Perform comprehensive health assessment.

        Args:
            state_msg: Latest state estimate message
        """
        # 1. Capacity fade analysis
        self._assess_capacity_fade(state_msg)

        # 2. Resistance increase analysis
        self._assess_resistance_increase(state_msg)

        # 3. RUL estimation
        self._estimate_rul(state_msg)

        # 4. Overall health status
        self._update_health_status(state_msg)

        # 5. Risk level assessment
        self._update_risk_level()

    def _assess_capacity_fade(self, state_msg: StateEstimateMessage):
        """Analyze capacity fade from SoH trends."""
        current_soh = state_msg.soh
        cycle = state_msg.cycle
        timestamp = datetime.fromtimestamp(state_msg.timestamp)

        # Calculate total fade
        fade_percent = (self.initial_soh - current_soh) * 100.0

        # Calculate fade rate (need at least 10 cycles for meaningful estimate)
        if len(self.soh_history) >= 10:
            # Linear regression on recent history
            recent_cycles = [c for c, _, _ in self.soh_history[-50:]]
            recent_soh = [s for _, s, _ in self.soh_history[-50:]]

            if len(recent_cycles) >= 2:
                # Fit line: soh = a + b * cycle
                coeffs = np.polyfit(recent_cycles, recent_soh, 1)
                fade_rate = -coeffs[0] * 100.0  # Percent per cycle (negative slope)
            else:
                fade_rate = 0.0
        else:
            # Not enough data yet
            if cycle > 0:
                fade_rate = fade_percent / cycle
            else:
                fade_rate = 0.0

        # Create metrics object
        self.latest_capacity_fade = CapacityFadeMetrics(
            initial_soh=self.initial_soh,
            current_soh=current_soh,
            fade_percent=fade_percent,
            fade_rate=fade_rate,
            cycles_observed=cycle,
            timestamp=timestamp
        )

        # Update beliefs
        self.state.update_belief(
            key='capacity_fade_rate',
            proposition=f"fade_rate_{fade_rate:.4f}",
            confidence=0.9,
            is_internal=True
        )

        self.logger.debug(
            f"Capacity fade: {fade_percent:.2f}% total, "
            f"{fade_rate:.4f}%/cycle"
        )

    def _assess_resistance_increase(self, state_msg: StateEstimateMessage):
        """Analyze resistance increase from R0 trends."""
        current_r0 = state_msg.r0
        cycle = state_msg.cycle
        timestamp = datetime.fromtimestamp(state_msg.timestamp)

        # Calculate total increase
        increase_percent = ((current_r0 - self.initial_r0) / self.initial_r0) * 100.0

        # Calculate increase rate
        if len(self.r0_history) >= 10:
            recent_cycles = [c for c, _, _ in self.r0_history[-50:]]
            recent_r0 = [r for _, r, _ in self.r0_history[-50:]]

            if len(recent_cycles) >= 2:
                coeffs = np.polyfit(recent_cycles, recent_r0, 1)
                increase_rate = coeffs[0]  # Ohms per cycle
            else:
                increase_rate = 0.0
        else:
            if cycle > 0:
                increase_rate = (current_r0 - self.initial_r0) / cycle
            else:
                increase_rate = 0.0

        # Create metrics object
        self.latest_resistance = ResistanceMetrics(
            initial_r0=self.initial_r0,
            current_r0=current_r0,
            increase_percent=increase_percent,
            increase_rate=increase_rate,
            cycles_observed=cycle,
            timestamp=timestamp
        )

        # Update beliefs
        self.state.update_belief(
            key='resistance_increase_rate',
            proposition=f"resistance_rate_{increase_rate:.6f}",
            confidence=0.9,
            is_internal=True
        )

        self.logger.debug(
            f"Resistance increase: {increase_percent:.2f}% total, "
            f"{increase_rate:.6f} Ω/cycle"
        )

    def _estimate_rul(self, state_msg: StateEstimateMessage):
        """Estimate Remaining Useful Life based on degradation trends."""
        current_soh = state_msg.soh
        timestamp = datetime.fromtimestamp(state_msg.timestamp)

        # Need capacity fade rate to estimate RUL
        if self.latest_capacity_fade is None or len(self.soh_history) < 10:
            # Not enough data yet
            self.latest_rul = RULEstimate(
                rul_cycles=float('inf'),
                rul_days=None,
                confidence=0.0,
                eol_threshold=self.eol_threshold,
                timestamp=timestamp
            )
            return

        fade_rate = self.latest_capacity_fade.fade_rate

        # Extrapolate to end-of-life threshold
        if fade_rate > 1e-6:  # Avoid division by zero
            # Remaining SoH to reach EOL
            remaining_soh = current_soh - self.eol_threshold

            # RUL in cycles (convert fade_rate from percent to absolute)
            rul_cycles = (remaining_soh / (fade_rate / 100.0))

            # Ensure non-negative
            rul_cycles = max(0.0, rul_cycles)

            # Confidence based on data quality
            if len(self.soh_history) >= 50:
                confidence = 0.9
            elif len(self.soh_history) >= 20:
                confidence = 0.7
            else:
                confidence = 0.5
        else:
            # No measurable degradation yet
            rul_cycles = float('inf')
            confidence = 0.1

        # Create RUL estimate
        self.latest_rul = RULEstimate(
            rul_cycles=rul_cycles,
            rul_days=None,  # Would need usage pattern
            confidence=confidence,
            eol_threshold=self.eol_threshold,
            timestamp=timestamp
        )

        # Update beliefs
        rul_str = "infinite" if rul_cycles == float('inf') else f"{rul_cycles:.1f}"
        self.state.update_belief(
            key='rul_cycles',
            proposition=f"rul_{rul_str}",
            confidence=confidence,
            is_internal=True
        )

        self.logger.debug(
            f"RUL estimate: {rul_cycles:.1f} cycles "
            f"(confidence={confidence:.2f})"
        )

    def _update_health_status(self, state_msg: StateEstimateMessage):
        """Update overall health status based on SoH."""
        soh = state_msg.soh

        # Classify health status
        if soh >= 0.95:
            status = HealthStatus.EXCELLENT
        elif soh >= 0.85:
            status = HealthStatus.GOOD
        elif soh >= 0.70:
            status = HealthStatus.FAIR
        elif soh >= 0.50:
            status = HealthStatus.POOR
        else:
            status = HealthStatus.CRITICAL

        # Update belief
        old_status_belief = self.state.get_belief('health_status')
        # Extract status from proposition (format: "status_EXCELLENT")
        old_status_str = old_status_belief.proposition.replace("status_", "") if old_status_belief else None

        self.state.update_belief(
            key='health_status',
            proposition=f"status_{status.value}",
            confidence=0.95,
            is_internal=True
        )

        # Generate alert if status changed
        if old_status_str and old_status_str != status.value:
            self._generate_alert(
                alert_type=AlertType.HEALTH_STATUS_CHANGE,
                severity=self._status_to_risk(status),
                message=f"Health status changed from {old_status_str} to {status.value}",
                metrics={'old_status': old_status_str, 'new_status': status.value, 'soh': soh}
            )

        self.logger.debug(f"Health status: {status.value} (SoH={soh:.4f})")

    def _update_risk_level(self):
        """Update risk level based on multiple factors."""
        # Get current metrics from actual stored values (not beliefs)
        soh = self.latest_capacity_fade.current_soh if self.latest_capacity_fade else self.initial_soh
        fade_rate = self.latest_capacity_fade.fade_rate if self.latest_capacity_fade else 0.0

        # Determine risk level
        risk = RiskLevel.LOW

        # Check SoH thresholds
        if soh < 0.60:
            risk = RiskLevel.CRITICAL
        elif soh < 0.75:
            risk = RiskLevel.HIGH
        elif soh < 0.90:
            risk = RiskLevel.MEDIUM

        # Check degradation rate
        if fade_rate > self.rapid_degradation_threshold:
            # Rapid degradation increases risk
            if risk == RiskLevel.LOW:
                risk = RiskLevel.MEDIUM
            elif risk == RiskLevel.MEDIUM:
                risk = RiskLevel.HIGH

        # Check RUL
        if self.latest_rul and self.latest_rul.rul_cycles < self.low_rul_threshold:
            if risk == RiskLevel.LOW:
                risk = RiskLevel.MEDIUM
            elif risk == RiskLevel.MEDIUM:
                risk = RiskLevel.HIGH

        # Update belief
        self.state.update_belief(
            key='risk_level',
            proposition=f"risk_{risk.value}",
            confidence=0.9,
            is_internal=True
        )

        self.logger.debug(f"Risk level: {risk.value}")

    # ========================================================================
    # Deliberation and Alert Generation
    # ========================================================================

    def _deliberate_on_alerts(self):
        """
        Deliberate on whether to generate alerts based on current beliefs.
        This is the core BDI deliberation logic.
        """
        # Check capacity fade threshold
        if self.latest_capacity_fade:
            if self.latest_capacity_fade.fade_percent >= self.capacity_fade_alert_threshold * 100:
                self._generate_alert(
                    alert_type=AlertType.CAPACITY_FADE,
                    severity=RiskLevel.MEDIUM,
                    message=f"Capacity fade {self.latest_capacity_fade.fade_percent:.2f}% exceeds threshold",
                    metrics={
                        'fade_percent': self.latest_capacity_fade.fade_percent,
                        'fade_rate': self.latest_capacity_fade.fade_rate,
                        'threshold': self.capacity_fade_alert_threshold * 100
                    },
                    recommended_action="Monitor closely, consider battery replacement planning"
                )

        # Check resistance increase threshold
        if self.latest_resistance:
            if self.latest_resistance.increase_percent >= self.resistance_increase_alert_threshold * 100:
                self._generate_alert(
                    alert_type=AlertType.RESISTANCE_INCREASE,
                    severity=RiskLevel.MEDIUM,
                    message=f"Resistance increase {self.latest_resistance.increase_percent:.2f}% exceeds threshold",
                    metrics={
                        'increase_percent': self.latest_resistance.increase_percent,
                        'increase_rate': self.latest_resistance.increase_rate,
                        'threshold': self.resistance_increase_alert_threshold * 100
                    },
                    recommended_action="Check for temperature stress or charging issues"
                )

        # Check rapid degradation
        if self.latest_capacity_fade:
            if self.latest_capacity_fade.fade_rate >= self.rapid_degradation_threshold:
                self._generate_alert(
                    alert_type=AlertType.RAPID_DEGRADATION,
                    severity=RiskLevel.HIGH,
                    message=f"Rapid degradation detected: {self.latest_capacity_fade.fade_rate:.4f}%/cycle",
                    metrics={
                        'fade_rate': self.latest_capacity_fade.fade_rate,
                        'threshold': self.rapid_degradation_threshold
                    },
                    recommended_action="Investigate operating conditions (temperature, current, voltage)"
                )

        # Check low RUL
        if self.latest_rul and self.latest_rul.rul_cycles < self.low_rul_threshold:
            severity = RiskLevel.HIGH if self.latest_rul.rul_cycles < 50 else RiskLevel.MEDIUM
            self._generate_alert(
                alert_type=AlertType.LOW_RUL,
                severity=severity,
                message=f"Low RUL: {self.latest_rul.rul_cycles:.0f} cycles remaining",
                metrics={
                    'rul_cycles': self.latest_rul.rul_cycles,
                    'confidence': self.latest_rul.confidence,
                    'threshold': self.low_rul_threshold
                },
                recommended_action="Plan battery replacement"
            )

    def _generate_alert(
        self,
        alert_type: AlertType,
        severity: RiskLevel,
        message: str,
        metrics: Dict,
        recommended_action: Optional[str] = None
    ):
        """Generate and record a health alert."""
        alert = HealthAlert(
            alert_type=alert_type,
            severity=severity,
            message=message,
            timestamp=datetime.now(),
            metrics=metrics,
            recommended_action=recommended_action
        )

        # Add to history (keep last 100)
        self.alert_history.append(alert)
        if len(self.alert_history) > 100:
            self.alert_history = self.alert_history[-100:]

        self.total_alerts_generated += 1

        # Update belief
        self.state.update_belief(
            key='alert_count',
            proposition=f"alerts_{self.total_alerts_generated}",
            confidence=1.0,
            is_internal=True
        )

        self.logger.warning(
            f"ALERT [{severity.value}] {alert_type.value}: {message}"
        )

    def _status_to_risk(self, status: HealthStatus) -> RiskLevel:
        """Convert health status to risk level."""
        if status == HealthStatus.CRITICAL:
            return RiskLevel.CRITICAL
        elif status == HealthStatus.POOR:
            return RiskLevel.HIGH
        elif status == HealthStatus.FAIR:
            return RiskLevel.MEDIUM
        else:
            return RiskLevel.LOW

    # ========================================================================
    # MQTT Publishing
    # ========================================================================

    def _publish_health_report(self, timestamp: float):
        """Publish health report to MQTT."""
        # Get current status using public API
        health_status = self.get_current_health_status().value
        risk_level = self.get_current_risk_level().value
        soh = self.latest_capacity_fade.current_soh if self.latest_capacity_fade else self.initial_soh

        # Get metrics
        capacity_fade_percent = self.latest_capacity_fade.fade_percent if self.latest_capacity_fade else 0.0
        capacity_fade_rate = self.latest_capacity_fade.fade_rate if self.latest_capacity_fade else 0.0
        resistance_increase_percent = self.latest_resistance.increase_percent if self.latest_resistance else 0.0
        # Handle RUL - use large number instead of infinity for JSON compatibility
        if self.latest_rul and self.latest_rul.rul_cycles != float('inf'):
            rul_cycles = self.latest_rul.rul_cycles
            rul_confidence = self.latest_rul.confidence
        else:
            rul_cycles = 999999.0  # Sentinel for "unknown/infinite"
            rul_confidence = 0.0

        # Get recent alerts (last 5)
        recent_alerts = [
            {
                'type': alert.alert_type.value,
                'severity': alert.severity.value,
                'message': alert.message,
                'timestamp': alert.timestamp.isoformat()
            }
            for alert in self.alert_history[-5:]
        ]

        # Generate recommendations
        recommendations = self._generate_recommendations()

        # Create message
        report = HealthReportMessage(
            battery_id=self.battery_id,
            timestamp=timestamp,
            health_status=health_status,
            risk_level=risk_level,
            soh=soh,
            capacity_fade_percent=capacity_fade_percent,
            capacity_fade_rate=capacity_fade_rate,
            resistance_increase_percent=resistance_increase_percent,
            rul_cycles=rul_cycles,
            rul_confidence=rul_confidence,
            alerts=recent_alerts,
            recommendations=recommendations
        )

        # Publish
        topic = f"battery/{self.battery_id}/health/report"
        if self.mqtt_bridge:
            self.mqtt_bridge.publish(topic, report.model_dump_json())
            self.logger.debug(f"Published health report to {topic}")

    def _generate_recommendations(self) -> List[str]:
        """Generate actionable recommendations based on current health."""
        recommendations = []

        # Based on health status - use public API
        health_status = self.get_current_health_status()
        if health_status == HealthStatus.CRITICAL:
            recommendations.append("URGENT: Replace battery immediately")
        elif health_status == HealthStatus.POOR:
            recommendations.append("Plan battery replacement within next maintenance window")
        elif health_status == HealthStatus.FAIR:
            recommendations.append("Monitor closely, schedule replacement planning")

        # Based on degradation rate
        if self.latest_capacity_fade and self.latest_capacity_fade.fade_rate > self.rapid_degradation_threshold:
            recommendations.append("Investigate operating conditions causing rapid degradation")

        # Based on RUL
        if self.latest_rul and self.latest_rul.rul_cycles < 50:
            recommendations.append("Prepare replacement battery, RUL < 50 cycles")

        return recommendations

    # ========================================================================
    # Public API
    # ========================================================================

    def get_current_health_status(self) -> HealthStatus:
        """Get current health status."""
        belief = self.state.get_belief('health_status')
        if belief:
            # Extract from proposition format: "status_EXCELLENT" -> "EXCELLENT"
            status_str = belief.proposition.replace("status_", "")
            return HealthStatus(status_str)
        return HealthStatus.EXCELLENT

    def get_current_risk_level(self) -> RiskLevel:
        """Get current risk level."""
        belief = self.state.get_belief('risk_level')
        if belief:
            # Extract from proposition format: "risk_LOW" -> "LOW"
            risk_str = belief.proposition.replace("risk_", "")
            return RiskLevel(risk_str)
        return RiskLevel.LOW

    def get_capacity_fade_metrics(self) -> Optional[CapacityFadeMetrics]:
        """Get latest capacity fade metrics."""
        return self.latest_capacity_fade

    def get_resistance_metrics(self) -> Optional[ResistanceMetrics]:
        """Get latest resistance metrics."""
        return self.latest_resistance

    def get_rul_estimate(self) -> Optional[RULEstimate]:
        """Get latest RUL estimate."""
        return self.latest_rul

    def get_recent_alerts(self, n: int = 10) -> List[HealthAlert]:
        """Get n most recent alerts."""
        return self.alert_history[-n:]

    def get_statistics(self) -> Dict:
        """Get agent statistics."""
        return {
            'total_assessments': self.total_assessments,
            'total_alerts_generated': self.total_alerts_generated,
            'current_cycle': self.current_cycle,
            'soh_history_length': len(self.soh_history),
            'r0_history_length': len(self.r0_history),
            'alert_history_length': len(self.alert_history)
        }
