apiVersion: 1

datasources:
  - name: InfluxDB-AgentSystem
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: agent_metrics
    user: agent_user
    password: password123
    isDefault: true
    jsonData:
      httpMode: GET
      keepCookies: []
    secureJsonData:
      password: password123
    version: 1
    editable: true